# -*- coding: utf-8 -*-
"""APLICACIÓN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVosAkGx-LONnzd0YB9_wZMQYu8uRKuP
"""

from functools import reduce

def calcular_media(datos):
    return reduce(lambda acc, x: acc + x, datos, 0) / len(datos) if datos else 0

def calcular_varianza(datos):
    if not datos:
        return 0
    media = calcular_media(datos)
    return reduce(lambda acc, x: acc + (x - media) ** 2, datos, 0) / len(datos)

# Solicitar entrada del usuario
calificaciones = list(map(float, input("Ingrese las calificaciones separadas por espacios: ").split()))

# Cálculo de estadísticas
media_calificaciones = calcular_media(calificaciones)
varianza_calificaciones = calcular_varianza(calificaciones)

print(f"Media de calificaciones: {media_calificaciones}")
print(f"Varianza de calificaciones: {varianza_calificaciones}")